CREATE TABLE [dbo].[CANAL_CONTACTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CEDULA] [nvarchar](max) NULL,
	[CONSULTA] [nvarchar](max) NULL,
	[TIPO] [nvarchar](max) NULL,
	[FECHA] [datetime] NULL,
 CONSTRAINT [PK_CANAL_CONTACTO1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CANAL_CONTACTO] ADD  CONSTRAINT [DF_CANAL_CONTACTO1_FECHA]  DEFAULT (getdate()) FOR [FECHA]
GO